# add doxygen docs
# to get paraview debian/build properly on top of vtk we now add this as a symlink 
# in the python3-vtk7 package 
# /opt/ros_industrial/vtk-7.1/lib/*/python3.5/site-packages/vtk/*
CMake/TopologicalSort.cmake opt/ros_industrial/vtk-7.1/lib/cmake/vtk-7.1/
CMake/vtkGroups.cmake opt/ros_industrial/vtk-7.1/lib/cmake/vtk-7.1/
CMake/vtkTesting*.cmake	opt/ros_industrial/vtk-7.1/lib/cmake/vtk-7.1/
Common/DataModel/vtkMarchingCubesTriangleCases.h opt/ros_industrial/vtk-7.1/include/vtk-7.1/
Filters/Statistics/vtkStatisticsAlgorithmPrivate.h opt/ros_industrial/vtk-7.1/include/vtk-7.1/
IO/Import/vtk3DS.h opt/ros_industrial/vtk-7.1/include/vtk-7.1/
Testing/Core/vtkTestDriver.h opt/ros_industrial/vtk-7.1/include/vtk-7.1
Testing/Core/vtkTestUtilities.h opt/ros_industrial/vtk-7.1/include/vtk-7.1/
Testing/Core/vtkTesting*.h opt/ros_industrial/vtk-7.1/include/vtk-7.1
Testing/Rendering/vtkRegressionTestImage.h opt/ros_industrial/vtk-7.1/include/vtk-7.1/
Testing/Rendering/vtkTesting*.h opt/ros_industrial/vtk-7.1/include/vtk-7.1
Wrapping/Java/JavaDependencies.cmake.in opt/ros_industrial/vtk-7.1/lib/cmake/vtk-7.1/
debian/build/ThirdParty/netcdf/vtk_netcdf.h opt/ros_industrial/vtk-7.1/include/vtk-7.1/
debian/build/ThirdParty/netcdf/vtk_netcdfcpp.h opt/ros_industrial/vtk-7.1/include/vtk-7.1/
debian/build/lib/cmake/vtk-7.1/Modules/*-Headers.cmake	opt/ros_industrial/vtk-7.1/lib/cmake/vtk-7.1/Modules/
opt/ros_industrial/vtk-7.1/include/vtk-7.1                    opt/ros_industrial/vtk-7.1/include
opt/ros_industrial/vtk-7.1/lib/*/*.so
opt/ros_industrial/vtk-7.1/lib/cmake/vtk-7.1
opt/ros_industrial/vtk-7.1/share/doc/vtk-7.1/doxygen/* /opt/ros_industrial/vtk-7.1/share/vtk-7.1/doxygen/
